"""Turn a deck specification into a presentation.

The only thing this module decides is which layout function handles which spec
and what page number it gets. Everything else was settled upstream: content by
the spec builder, position by the layout.
"""

from __future__ import annotations

import datetime as dt
import logging
from pathlib import Path

from pptx.presentation import Presentation as PresentationType

from deckpilot.renderer import (
    agenda,
    benefits_bridge,
    criteria_columns,
    exec_summary,
    financial_summary,
    governance_chart,
    kpi_scorecard,
    raid_table,
    roadmap_gantt,
    section_divider,
    status_overview,
    workstream_charter,
)
from deckpilot.renderer.base import new_deck
from deckpilot.specgen.schema import DeckSpec

log = logging.getLogger("deckpilot.renderer")

GENERATOR = "deckpilot"

# A section divider takes no page number - it carries no footer - but it still
# occupies a page, so the count runs through it.
RENDERERS = {
    "section_divider": lambda prs, spec, page: section_divider.render(prs, spec),
    "workstream_charter": workstream_charter.render,
    "roadmap_gantt": roadmap_gantt.render,
    "governance_chart": governance_chart.render,
    "raid_table": raid_table.render,
    "status_overview": status_overview.render,
    "criteria_columns": criteria_columns.render,
    "exec_summary": exec_summary.render,
    "kpi_scorecard": kpi_scorecard.render,
    "agenda": agenda.render,
    "benefits_bridge": benefits_bridge.render,
    "financial_summary": financial_summary.render,
}


def _set_properties(prs: PresentationType, spec: DeckSpec) -> None:
    """Fill in the document properties, which are not ours until we set them.

    python-pptx builds every deck from a default template, and that template's
    core properties come with it: a creation date in 2013 and the library
    maintainer's name in "last modified by". Nobody notices until someone
    right-clicks the file, and then it looks like the deck came from a stranger.

    The dates are the end of the reported week rather than the moment of the
    build, so the same input still produces the same file. A deck that carries no
    real week - a single layout rendered on its own - keeps whatever dates it had
    rather than inventing one.
    """
    core = prs.core_properties
    core.title = spec.title
    core.subject = spec.subtitle
    core.author = spec.title
    core.last_modified_by = GENERATOR
    core.comments = f"Generated by {GENERATOR} for week {spec.week}"
    core.category = ""
    core.keywords = spec.week
    core.revision = 1

    reported = _week_end(spec.week)
    if reported is not None:
        core.created = reported
        core.modified = reported


def _drop_template_thumbnail(prs: PresentationType) -> None:
    """Remove the preview image inherited from python-pptx's default template.

    It is a picture of a slide from a 2013 sample deck, and it is what Finder and
    Explorer show as the file's preview until someone opens the deck in
    PowerPoint and saves it. Removing it leaves no preview, which is honest;
    leaving it shows the wrong one.
    """
    package = prs.part.package
    for rid, rel in list(package._rels.items()):
        if rel.reltype.rsplit("/", 1)[-1] == "thumbnail":
            package.drop_rel(rid)


def _week_end(week: str) -> dt.datetime | None:
    """The Friday of an ISO week, or None if this is not a real week."""
    try:
        year, number = week.split("-W")
        return dt.datetime.fromisocalendar(int(year), int(number), 5)
    except (ValueError, IndexError):
        return None


def build(spec: DeckSpec) -> PresentationType:
    prs = new_deck()
    for page, slide_spec in enumerate(spec.slides, start=1):
        render = RENDERERS.get(slide_spec.layout)
        if render is None:  # pragma: no cover - the schema forbids it
            raise KeyError(f"no renderer for layout {slide_spec.layout!r}")
        slide = render(prs, slide_spec, page)
        _attach_notes(slide, slide_spec.notes)
    _set_properties(prs, spec)
    _drop_template_thumbnail(prs)
    return prs


def _attach_notes(slide, notes: str) -> None:
    """Write the speaker notes, if there are any.

    Touching `notes_slide` creates one, so an empty note is skipped rather than
    written blank - a deck full of empty notes pages is a deck that looks like it
    has notes.
    """
    if not notes:
        return
    slide.notes_slide.notes_text_frame.text = notes


def build_to(spec: DeckSpec, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    build(spec).save(str(path))
    log.info("wrote %s (%d slides)", path, len(spec.slides))
    return path
